name: Android CI

on:
  push:
    branches: [ main, master, develop, "**" ]
  pull_request:
    branches: [ "**" ]

env:
  ANDROID_COMPILE_SDK: 36
  ANDROID_BUILD_TOOLS: 36.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" \
                    "platforms;android-${ANDROID_COMPILE_SDK}" \
                    "build-tools;${ANDROID_BUILD_TOOLS}"

      - name: Build Debug APK
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Run unit tests
        run: ./gradlew --no-daemon testDebugUnitTest

      # Sign and build Release only if secrets are present
      - name: Decode release keystore
        if: ${{ secrets.RELEASE_STORE_FILE_B64 != '' }}
        run: echo "$RELEASE_STORE_FILE_B64" | base64 -d > app/release.keystore
        env:
          RELEASE_STORE_FILE_B64: ${{ secrets.RELEASE_STORE_FILE_B64 }}

      - name: Build signed Release AAB and APK
        if: ${{ secrets.RELEASE_STORE_FILE_B64 != '' }}
        env:
          ORG_GRADLE_PROJECT_RELEASE_STORE_FILE: app/release.keystore
          ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          ./gradlew --no-daemon assembleRelease bundleRelease

      - name: Upload release artifacts
        if: ${{ secrets.RELEASE_STORE_FILE_B64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
